update notif

diff --git a/.circleci/pr-notifications.yml b/.circleci/pr-notifications.yml
--- a/.circleci/pr-notifications.yml
+++ b/.circleci/pr-notifications.yml
@@ -1,9 +1,7 @@
 version: 2.1
 
-parameters:
-  commit_sha:
-    type: string
-    default: ""
+orbs:
+  slack: circleci/slack@5.1.1
 
 jobs:
   webhook-notify-on-fail:
@@ -24,9 +22,14 @@ jobs:
 
             if [ "$WORKFLOW_STATUS" = "failed" ]; then
                 echo -e "Hi $COMMIT_AUTHOR.\nThe workflow '$WORKFLOW_NAME' completed with the status '$WORKFLOW_STATUS'.\nYou can view this workflow here: '$WORKFLOW_URL'"
+                # failing in order to trigger the Slack notification
+                exit 1
             else
                 echo "workflow did not fail. No need to send a notification"
             fi
+      - slack/notify:
+          channel: ABC123
+          template: basic_fail_1
 
   pipeline-notify-on-fail:
     docker:
